"""Add User model and attach to Conversation

Revision ID: 18d49dbea9b3
Revises: 
Create Date: 2026-07-26 18:06:34.506293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d49dbea9b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_conversations_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document_relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_article_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target_article_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_relationships_source_article_id'), ['source_article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_relationships_target_article_id'), ['target_article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_relationships_target_doc_ref'), ['target_doc_ref'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_ngay_ban_hanh'), ['ngay_ban_hanh'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_ngay_hieu_luc'), ['ngay_hieu_luc'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_verification_status'), ['source_verification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_validity_confidence'), ['validity_confidence'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_validity_confidence'))
        batch_op.drop_index(batch_op.f('ix_documents_source_verification_status'))
        batch_op.drop_index(batch_op.f('ix_documents_ngay_hieu_luc'))
        batch_op.drop_index(batch_op.f('ix_documents_ngay_ban_hanh'))

    with op.batch_alter_table('document_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_relationships_target_doc_ref'))
        batch_op.drop_index(batch_op.f('ix_document_relationships_target_article_id'))
        batch_op.drop_index(batch_op.f('ix_document_relationships_source_article_id'))
        batch_op.drop_column('target_article_id')
        batch_op.drop_column('source_article_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
